### ISSUE TITLE
Define a type Index = (i32, usize) and use this to refer to elements

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#29]

**Comment by hoodmane** [comment]
Any reason why (i32, usize) and not (u32, i32, usize)?

**Comment by dalcde** [comment]
(i32, usize) seems to be the combination that appears more frequently,
e.g. in multiply_basis_elements, get_filtration_one_product, etc.

**Comment by hoodmane** [comment]
I guess that makes sense. Probably we should have both types around.

**Comment by hoodmane** [comment]
Perhaps GradedBasisElement and BigradedBasisElement or something like that.

**Comment by dalcde** [comment]
I personally prefer shorter names...

Speaking of which, I would also prefer more descriptive names for
"Table".

**Comment by hoodmane** [comment]
GradedGen and BigradedGen? Gen and BiGen? 

Feel free to change any names that you think are too bland. If I called something "table" that's like saying "I'm too lazy to name this right now".

**Comment by hoodmane** [comment]
Index and BiIndex?

**Comment by dalcde** [comment]
What would BiIndex be?

**Comment by hoodmane** [comment]
(u32, i32, usize) -- so a basis element of a bigraded vector space (like a basis element of ext for instance).

**Comment by dalcde** [comment]
Oh right of course.

**Comment by dalcde** [comment]
Now that I actually try to implement this, this does not seem like a good idea after all, since we have to spend extra effort deconstructing the tuple every time we use this.
