### ISSUE TITLE
cli_module_loader produces incorrect Adem actions at p > 2

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#35]
For example, if you try to build S/(3, v_1), you get the following:
```
{"input":"x0",
 "op":[1],
 "output":[{"coeff":1,"gen":"x1"}]},
{"input":"x0",
 "op":[1,1,0],
 "output":[]},
{"input":"x0",
 "op":[0,1,1],
 "output":[{"coeff":1,"gen":"x5"}]}...
```
The second one should correspond to P¹βx₀ = x₅, while the third should be βP¹x₀ = 0. This causes the resolver to crash when trying to resolve this module .

I think this is due to inconsistency in deciding whether you are listing your Bocksteins/Steenrod operations left-to-right or right-to-left. In any case this should probably be clearly documented at `AdemBasisElement`.

**Comment by hoodmane** [comment]
I fixed it.
