### ISSUE TITLE
WebSocket interface should understand products as well

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#36]
Add a method to introduce products after the resolution is produced. Perhaps resolve both Ext(k, k) and Ext(M, k) and let users select it from Ext(k, k).

**Comment by hoodmane** [comment]
The backend already supports this. You need to call 
```
res_with_maps.add_product(hom_deg, int_deg, index, name);
res_with_maps.compute_products(homological_degree, internal_degree);
```

**Comment by hoodmane** [comment]
I think we should implement serialization and load `Ext(k, k)` from a file. The server version can extend the unit resolution if the range requested is larger than the size of the stored information and then store the larger range.

**Comment by dalcde** [comment]
I agree serialization is a nice thing to have, but probably not that
essential for this purpose. It currently takes around half a second for
me to cmpute Ext(k, k) up to degree 50 at p = 2.

**Comment by hoodmane** [comment]
Just seems annoying that now whenever we resolve anything, we actually have to compute two resolutions. As you say it's not essential.

**Comment by dalcde** [comment]
It seems like you will have to manually call compute_product for all bidegrees if you do it after the resolution is computed
