### ISSUE TITLE
Interface to recursively view cocycle string

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#67]

**Comment by hoodmane** [comment]
What does "recursively" mean here?

**Comment by dalcde** [comment]
For example, if we want to inspect c_0, first we know c_0 kills Sq^7
h_1^2 + Sq^4 Sq^2 Sq^1 h_1^2 + ...  and then figure out what h_1^2 etc.
kills, and then do this recursively until we hit s = 0, and display all
of this in a tree-like manner.

The main difficulty is in finding a reasonable way to display this.

**Comment by hoodmane** [comment]
What is this good for? Like is there a use case where you want to be able to quickly query this sort of thing? I can see that if you use the normal interface, you have to hunt down each of the cocycles that appears in d(x) in the display and that could take a lot of time, so if you are doing this sort of thing a lot you might want a feature for it...

**Comment by dalcde** [comment]
It might be useful for finding/thinking about small Yoneda
representatives. Otherwise, not much.
