### ISSUE TITLE
Calculate Steenrod operations

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#68]
- [x] Define direct sum and tensor products of modules
- [x] Define tensor product of chain complexes
- [x] Refactor `ResolutionHomomorphism` so that the target can be an arbitrary chain complex. Introduce a new trait "chain complex with quasi-inverse" which allows for customized implementation of quasi-inverse for the tensor product.
- [x] Actually do the calculation. The algorithm here may be useful: https://arxiv.org/abs/1909.03117 . If we can implement a somewhat effective way of producing the Yoneda representative of a class, this may help us speed up product calculations a lot as well.

**Comment by hoodmane** [comment]
Regarding yoneda representatives, someone should talk to Bob Bruner about it. I hear Christian Nassau is also good about responding to email.
