### ISSUE TITLE
Steenrod operations is currently broken

### ISSUE THREAD

**Issue by dalcde** [hoodmane/rust_ext#83]
The error is here: https://github.com/hoodmane/rust_ext/commit/3718b9c60974181c2ca20ce2fa15a7b0c5b7f8b3#diff-6db24994b64d9c0c008ab5e7d3a20426R30

This crashes when `self.left.dimension(left_degree) == 0`.

I should have added some unit tests...

**Comment by hoodmane** [comment]
Well you can always add unit tests now. 

I tried to improve the testing and documentation a little bit, though it was really only a burst of irresponsibility over the weekend that I worked on this. Have to go back to not touching it for another few months.
